agenda/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from agenda import views

app_name = 'agenda'

contact_api_router = SimpleRouter()
contact_api_router.register(
    'api',
    views.ContactAPIViewSet,
    basename='api'
)


urlpatterns = [
     path('', views.ListViewHome.as_view(), name='home'),
     path(
          'view_contact/<int:pk>/',
          views.DetalViewContact.as_view(),
          name='view_contact'
          ),

     path(
          'add_contact/',
          views.ContactCreateView.as_view(),
          name='add_contact'
          ),
     path(
          'update_contact/<int:pk>/',
          views.ContactUpdateView.as_view(),
          name='update_contact'
          ),
     path(
          'remove_contact/<int:pk>/',
          views.ContactDeleteView.as_view(),
          name='remove_contact'
          ),

     path(
          'add_category/',
          views.CategoryCreateView.as_view(),
          name='add_category'
          ),
     path(
          'remove_category/',
          views.CategoryDeleteView.as_view(),
          name='remove_category'
          ),
     path(
          'update_category/',
          views.CategoryUpdateView.as_view(),
          name='update_category'
          ),

     path('search/', views.ListViewSearch.as_view(), name='search'),

     # path(
     #      'api/',
     #      views.ContactAPIViewSet.as_view(),
     #      name='contact_api'
     #      ),

     # path(
     #      'api/<int:pk>/',
     #      views.ContactAPIViewSet.as_view(),
     #      name='contact_api_detail'
     #      ),

     path(
          'api/category/<int:pk>/',
          views.CategoryAPIDetailView.as_view(),
          name='category_api_detail'
          ),
]

urlpatterns += contact_api_router.urls

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agenda.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=55)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    date_created = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True)
    cover = models.ImageField(
        upload_to='contact/covers/%Y/%m/%d/', blank=True, default='')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

agenda/views/agenda_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import DetailView, ListView

from agenda.models import Contact


class ListViewBase(LoginRequiredMixin, ListView):
    login_url = 'authors:login_author'
    template_name = 'agenda/pages/home.html'
    model = Contact
    paginate_by = 2
    context_object_name = 'contacts'
    paginator_class = Paginator

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(
            user=self.request.user
        ).order_by('-id')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Home',
            'user': self.request.user
        })

        return context


class ListViewHome(ListViewBase):
    login_url = 'authors:login_author'
    template_name = 'agenda/pages/home.html'


class ListViewSearch(ListViewBase):
    login_url = 'authors:login_author'
    template_name = 'agenda/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        queryset = queryset.filter(
            Q(user=self.request.user) & (
                Q(id__icontains=search_term) |
                Q(first_name__icontains=search_term) |
                Q(last_name__icontains=search_term) |
                Q(phone__icontains=search_term) |
                Q(email__icontains=search_term)
            )
        ).order_by('-id')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        context.update({
            'search_term': search_term,
            'title': 'Search'
        })

        return context


class DetalViewContact(LoginRequiredMixin, DetailView):
    login_url = 'authors:login_author'
    template_name = 'agenda/pages/view_contact.html'
    model = Contact
    context_object_name = 'contact'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(
            pk=self.kwargs.get('pk'),
            user=self.request.user
        )

        return queryset

agenda/views/api.py
from rest_framework.generics import RetrieveAPIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet

from agenda.models import Category, Contact
from agenda.serializers import CategorySerializer, ContactSerializer


class ContactAPIPagination(PageNumberPagination):
    page_size = 5


class ContactAPIViewSet(ModelViewSet):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
    pagination_class = ContactAPIPagination


class CategoryAPIDetailView(RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

agenda/views/crud_category_views.py
from django.shortcuts import get_object_or_404
from agenda.form import CategoryForm, RemoveCategoryForm, UpdateCategoryForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from agenda.models import Category


class CategoryCreateView(LoginRequiredMixin, CreateView):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_page.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('agenda:home')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Add Category',
            'msg': 'Category',
        })

        return context


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_page.html'
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy('agenda:home')

    def get_object(self, queryset=None):
        return get_object_or_404(Category, user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Passa o user para o formulário
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Update Category',
            'msg': 'Update Category',
        })

        return context


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_page.html'
    model = Category
    form_class = RemoveCategoryForm
    success_url = reverse_lazy('agenda:home')

    def get_object(self, queryset=None):
        return get_object_or_404(Category, user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Remove Category',
            'msg': 'Remove Category',
        })

        return context

agenda/views/crud_contact_views.py
from agenda.models import Contact
from agenda.form import ContactForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect


class ContactViewSettingsMixin(LoginRequiredMixin):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_page.html'
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('agenda:home')


class ContactCreateView(ContactViewSettingsMixin, CreateView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Category',
            'msg': 'Profile',
        })

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)


class ContactUpdateView(ContactViewSettingsMixin, UpdateView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Update Contact',
            'msg': 'Profile',
        })

        return context


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'authors:login_author'
    model = Contact
    template_name = None
    success_url = reverse_lazy('agenda:home')

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return HttpResponseRedirect(self.success_url)

agenda/templates/agenda/pages/home.html
{% extends "global/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="contact-background">
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    <div class="contacts">
        <h2>Contacts</h2>
    </div>
    <table>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone</th>
            <th>Email</th>
        </tr>
        {% for contact in page_obj %}
            <tr>
                <td><a href="{% url 'agenda:view_contact' contact.id %}" class="td-a-contact">{{ contact.id }}</a></td>
                <td>{{ contact.first_name }}</td>
                <td>{{ contact.last_name }}</td>
                <td>{{ contact.phone }}</td>
                <td>{{ contact.email }}</td>
            </tr>
            {% empty %}
                {% if title == 'Search' %}
                    <p>Search not found</p>
                {% endif %}
        {% endfor %}
    </table>
    <div >
        <form action="{% url "agenda:add_contact" %}" method="post">
            {% csrf_token %}
            <br><button type="submit" class="contact-button">Add</button>
        </form>
    </div>

    <br><div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

agenda/templates/agenda/pages/update_contact.html
{% extends "global/base.html" %}

{% block title %}Update contact{% endblock title %}

{% block content %}
    <div class="contact-background">
        <div class="contact-profile">
            <h2>Profile</h2>
        </div>
        <div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        </div>
        <form action="{% url 'agenda:update_contact' contact.id %}" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="contact-forms">
                {% for field in form %}
                    <div class="field-contact-form">
                        {% if field.name == 'cover' %}
                             {% if field.value %}
                                <div class="currently-container">
                                    <span>Currently:</span> 
                                    <a href="{{ field.value.url }}" class="currently-image">{{ field.value.name }}</a>
                                </div><br>

                                <div class="clear-container">
                                    <label for="{{ field.name }}-clear_id">Clear:</label>
                                    <input type="checkbox" name="{{ field.name }}-clear" id="{{ field.name }}-clear_id" class="checkbox-large">
                                </div><br>
                             {% endif %}
                        {% else %}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
                            {{ field }}
                        {% endif %}
                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                Change:
                    <input type="file" name="cover" accept="image/*" id="id_cover">
            </div><br>
        
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
        
            <br><button type="submit" class="contact-button">Send</button>
        </form>
    </div>
{% endblock content %}

agenda/templates/agenda/pages/view_contact.html
{% extends "global/base.html" %}

{% block title %}View contact{% endblock title %}

{% block content %}
<div class="contact-background">
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="view_contact-contacts">
        <h2>{{ contact.first_name }} {{ contact.last_name }}</h2><br>
        <p><strong>ID: </strong>{{ contact.id }}</p>
        <p><strong>Phone: </strong>{{ contact.phone }}</p>
        <p><strong>Email: </strong>{{ contact.email }}</p>
        <p><strong>Date created: </strong>{{ contact.date_created }}</p>

        {% if contact.description %}
            <p><strong>Description: </strong>{{ contact.description }}</p>
        {% endif %}

        {% if contact.category != None %}
            <p><strong>Category: </strong>{{ contact.category }}</p>
        {% else %}
            <p><strong>Category: </strong>Unknow</p>
        {% endif %}
        {% if contact.cover %}
            <div>
                <img src="{{ contact.cover.url }}" alt="image" class="view_contact-recipe-cover-img">
            </div>
        {% endif %}
        <br><br><a href="{% url 'agenda:update_contact' contact.id %}" class="button-home">Update</a>

        <form action="{% url 'agenda:remove_contact' contact.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="button-home">Remove</button>
        </form>
    </div>
</div>
{% endblock content %}