agenda/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from agenda import views

app_name = 'agenda'

contact_api_router = SimpleRouter()
contact_api_router.register(
    'api',
    views.ContactAPIViewSet,
    basename='api'
)


urlpatterns = [
     path('', views.ListViewHome.as_view(), name='home'),
     path(
          'view_contact/<int:pk>/',
          views.DetalViewContact.as_view(),
          name='view_contact'
          ),

     path(
          'add_contact/',
          views.ContactCreateView.as_view(),
          name='add_contact'
          ),
     path(
          'update_contact/<int:pk>/',
          views.ContactUpdateView.as_view(),
          name='update_contact'
          ),
     path(
          'remove_contact/<int:pk>/',
          views.ContactDeleteView.as_view(),
          name='remove_contact'
          ),

     path(
          'add_category/',
          views.CategoryCreateView.as_view(),
          name='add_category'
          ),
     path(
          'remove_category/',
          views.CategoryDeleteView.as_view(),
          name='remove_category'
          ),
     path(
          'update_category/',
          views.CategoryUpdateView.as_view(),
          name='update_category'
          ),

     path('search/', views.ListViewSearch.as_view(), name='search'),

     # path(
     #      'api/',
     #      views.ContactAPIViewSet.as_view(),
     #      name='contact_api'
     #      ),

     # path(
     #      'api/<int:pk>/',
     #      views.ContactAPIViewSet.as_view(),
     #      name='contact_api_detail'
     #      ),

     path(
          'api/category/<int:pk>/',
          views.CategoryAPIDetailView.as_view(),
          name='category_api_detail'
          ),
]

urlpatterns += contact_api_router.urls

authors/urls.py
from django.urls import path
from authors import views


app_name = 'authors'


urlpatterns = [
    path('register_author/',
         views.AuthorRegisterView.as_view(),
         name='register_author'
         ),
    path('login_author/',
         views.AuthorLoginView.as_view(),
         name='login_author'
         ),
    path('logout_author/',
         views.AuthorLogoutView.as_view(),
         name='logout_author'
         ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agenda.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/views.py
from authors.form import RegisterForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect


class AuthorRegisterView(FormView):
    template_name = 'global/pages/base_page.html'
    form_class = RegisterForm
    success_url = reverse_lazy('agenda:home')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Register',
            'msg': 'Register',
        })

        return context

    def form_valid(self, form):
        form.save()

        return redirect(self.success_url)


class AuthorLoginView(LoginView):
    template_name = 'global/pages/base_page.html'
    success_url = reverse_lazy('agenda:home')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Login',
            'msg': 'Login',
            'dont_have_account': True,
        })

        return context

    def get_success_url(self):
        return self.success_url


class AuthorLogoutView(LoginRequiredMixin, LogoutView):
    login_url = 'authors:login_author'

    def get_redirect_url(self):
        return '/'

authors/templates/authors/pages/register_page.html
{% extends "global/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <div class="contact-background">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="contact-profile">
            <h2>{{ msg }}</h2>
        </div>
        <form action="{{ url_action }}" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="contact-forms">
                {% for field in form %}
                    <div class="field-contact-form">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
                        {{ field }}
                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                {% if error != "This field is required." %}
                                    <div class="error">{{ error }}</div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <button type="submit" class="contact-button">Send</button>
            {% if msg == 'Profile' %}
                <div class="button-container">
                    <a href="{% url 'agenda:add_category' %}" class="contact-button">Add New Category</a>
                    <a href="{% url 'agenda:remove_category' %}" class="contact-button">Remove a Category</a>
                    <a href="{% url 'agenda:update_category' %}" class="contact-button">Update a Category</a>
                </div>
            {% endif %}
        </form>
    </div>
{% endblock content %}